steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'delfos-ds-core-invoice/app-deploy', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'delfos-ds-core-invoice/app-deploy']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'app-container', '--image', 'delfos-ds-core-invoice/app-deploy', '--region', 'us-central1', '--port', '80', '--allow-unauthenticated']
images:
- delfos-ds-core-invoice/app-deploy